name: Build Project

on:
  push:
    branches:
      - build

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        repository: ambrosiogabe/MathAnimation
        submodules: recursive

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.21'

    - name: Setup YASM
      run: choco install yasm

    - name: Setup MSVC
      uses: TheMrMilchmann/setup-msvc-dev@v2
      with:
        arch: x64

    - name: Run Build
      run: |
        mkdir build
        pushd build
        cmake ..
        popd
