name: Build Project

on:
  push:
    branches:
      - build

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        repository: ambrosiogabe/MathAnimation
        submodules: recursive

    - name: Setup 7zip
      run: choco install 7zip

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.21'

    - name: Setup YASM
      run: choco install yasm

    - name: Setup MSVC
      uses: TheMrMilchmann/setup-msvc-dev@v2
      with:
        arch: x64

    - name: Configure Build
      run: |
        mkdir build
        pushd build
        cmake ..
        popd

    - name: Run build
      run: |
        cd build
        cmake --build . --parallel --target MathAnimations

    - name: Package Compiled Files
      run: |
        7z a -t7z -r MathAnimations.7z D:/a/MathAnimation/MathAnimation/build

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "MathAnimations.7z"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: release
        name: Automated Release
        replacesArtifacts: true
        allowUpdates: true
